# Generated by Django 2.0.8 on 2018-12-16 12:59

from django.db import migrations, models
import users.models.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endworker',
            name='group',
            field=models.IntegerField(default=users.models.utils.utils.get_group_number),
        ),
    ]
