# Generated by Django 2.0.8 on 2019-09-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190413_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='endworker',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='endworker',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='endworker',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
    ]
