# Generated by Django 2.0.8 on 2019-10-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190925_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='endworker',
            name='profile',
            field=models.IntegerField(default=1),
        ),
    ]
