# Generated by Django 2.2 on 2019-11-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_activationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='token',
            field=models.CharField(default='dd859f46503d484487e544787db5b3eb', max_length=32),
        ),
    ]
