# Generated by Django 2.2.7 on 2019-11-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191114_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='token',
            field=models.CharField(default='dba0d34899d2444e999dc89b83c361a8', max_length=32),
        ),
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.CharField(default='04bb64e35fc84e74bd8ee022038c3f4d', max_length=32),
        ),
    ]
