# Generated by Django 2.2.7 on 2019-11-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191114_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='token',
            field=models.CharField(default='e40358ec26404dafb1ae21d0bd660e89', max_length=32),
        ),
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.CharField(default='9f9b4200c9924a95b885b60f73cfd2b3', max_length=32),
        ),
    ]
