# Generated by Django 2.2.4 on 2019-12-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191128_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='token',
            field=models.CharField(default='906dbcc4c6014c88af7fddf836b42f38', max_length=32),
        ),
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.CharField(default='31f1f3c2957b4877962a127025fb4bba', max_length=32),
        ),
    ]
