# Generated by Django 2.2.4 on 2020-01-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191214_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='token',
            field=models.CharField(default='d4b5740e7d624ee1a5fa7c169156b1b1', max_length=32),
        ),
        migrations.AlterField(
            model_name='passwordtoken',
            name='token',
            field=models.CharField(default='3551deae0d2f46c09de5c4349aedb907', max_length=32),
        ),
    ]
