# Generated by Django 2.0.8 on 2019-02-05 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0010_auto_20190203_2307'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MissionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_done', models.IntegerField(default=0)),
                ('mission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_stats', to='tasks.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='UserMissionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_done', models.IntegerField(default=0)),
                ('mission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tasks.Mission')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_mission_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_done', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
