# Generated by Django 2.0.8 on 2019-02-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_auto_20190220_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermissionstats',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tasks.Mission'),
        ),
    ]
