# Generated by Django 2.0.8 on 2019-02-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0004_auto_20190220_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermissionstats',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
