# Generated by Django 2.0.8 on 2019-02-27 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0005_auto_20190221_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermissionstats',
            name='high_agreement_count',
        ),
    ]
