# Generated by Django 2.0.8 on 2019-02-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0007_remove_userstats_high_agreement_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermissionstats',
            name='_high_agreement_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='_high_agreement_count',
            field=models.IntegerField(default=0),
        ),
    ]
