# Generated by Django 2.0.8 on 2019-02-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0008_auto_20190228_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionstats',
            name='items_done',
        ),
        migrations.AddField(
            model_name='missionstats',
            name='agreement_mean',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usermissionstats',
            name='_annotated_documents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='_annotated_documents',
            field=models.IntegerField(default=0),
        ),
    ]
