# Generated by Django 2.0.8 on 2019-02-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0010_remove_missionstats_agreement_mean'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermissionstats',
            name='_annotated_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='_annotated_items',
            field=models.IntegerField(default=0),
        ),
    ]
