# Generated by Django 2.2.4 on 2019-12-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0012_auto_20190228_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='annotated_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
