version: '3.5'

networks:
  default:
    external:
      name: funcrowd-network

services:
  app:
    build: .
    container_name: funcrowd-app
    restart: always
    ports:
      - "8888:80"
      - "8080:8080"
    depends_on:
      - "db"
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      bash -c "./bin/wait-for-it.sh -t 360 ${POSTGRES_HOST}:${POSTGRES_PORT}
      && ./manage.py migrate --no-input
      && gunicorn funcrowd.wsgi --bind 0.0.0.0:80 --workers 2 --worker-class gevent --reload --access-logfile=-"

  notebook:
    build: .
    container_name: funcrowd-notebook
    restart: always
    ports:
      - "8888:80"
      - "8080:8080"
    depends_on:
      - "db"
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
        bash -c "./manage.py shell_plus --notebook"

  db:
    ports:
      - "5432:5432"
    image: postgres:13.0
    restart: always
    container_name: funcrowd-db
    volumes:
      - funcrowd_db:/var/lib/postgresql/data
      - ./backups:/var/lib/backups
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

volumes:
    funcrowd_db:

