# Generated by Django 2.0.8 on 2019-10-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20191001_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
