# Generated by Django 2.2.7 on 2019-11-28 23:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_auto_20191027_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
