# Generated by Django 2.2.4 on 2019-12-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_auto_20191128_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
