# Generated by Django 2.2.4 on 2020-02-16 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_assignprofileachievement_unlockmissionaftertaskachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignSpaceCalcGroupAchievement',
            fields=[
                ('achievement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='achievements.Achievement')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('achievements.achievement',),
        ),
    ]
