# Generated by Django 2.2.4 on 2020-03-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0010_achievement_auto_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='auto_close',
        ),
    ]
