# Generated by Django 2.0.8 on 2018-12-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='annotations_done',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='annotations_initial',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='created',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='user',
        ),
    ]
