# Generated by Django 2.0.8 on 2018-12-09 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bounty', '0002_auto_20181209_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('OPEN', 'OPEN'), ('FINISHED', 'FINISHED'), ('CLOSED', 'CLOSED')], default='NEW', max_length=10)),
                ('annotations_initial', models.IntegerField(default=0)),
                ('annotations_done', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bounties', to='bounty.Bounty')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
