# Generated by Django 2.0.8 on 2018-12-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0003_userbounty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbounty',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FINISHED', 'FINISHED'), ('CLOSED', 'CLOSED')], default='NEW', max_length=20),
        ),
    ]
