# Generated by Django 2.0.8 on 2018-12-09 22:40

from django.db import migrations, models
import modules.bounty.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0004_auto_20181209_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbounty',
            name='reward_token',
            field=models.CharField(default=modules.bounty.models.utils.get_reward_token, max_length=32),
        ),
    ]
