# Generated by Django 2.0.8 on 2018-12-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0006_bounty_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='finished',
            new_name='closed',
        ),
    ]
