# Generated by Django 2.0.8 on 2019-10-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0007_auto_20181218_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
