# Generated by Django 2.0.8 on 2019-10-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0008_bounty_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbounty',
            options={'ordering': ['-created']},
        ),
    ]
