# Generated by Django 2.2.4 on 2020-05-17 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_auto_20200513_2233'),
        ('bounty', '0009_auto_20191024_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bounty',
            name='annotations_target',
        ),
        migrations.RemoveField(
            model_name='bounty',
            name='task',
        ),
        migrations.RemoveField(
            model_name='userbounty',
            name='annotations_done',
        ),
        migrations.RemoveField(
            model_name='userbounty',
            name='annotations_initial',
        ),
        migrations.RemoveField(
            model_name='userbounty',
            name='updated',
        ),
        migrations.AddField(
            model_name='bounty',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bounties', to='packages.MissionPackages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbounty',
            name='package_progress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='packages.UserPackageProgress'),
            preserve_default=False,
        ),
    ]
