# Generated by Django 2.0.8 on 2018-11-22 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackScoreField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='fields',
            field=models.ManyToManyField(to='feedback.FeedbackField'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='score_fields',
            field=models.ManyToManyField(to='feedback.FeedbackScoreField'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Task'),
        ),
    ]
