# Generated by Django 2.0.8 on 2018-11-23 00:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('feedback', '0002_auto_20181122_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.Annotation')),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='tasks.Task'),
        ),
    ]
