# Generated by Django 2.0.8 on 2018-11-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20181123_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationfeedback',
            name='annotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='tasks.Annotation'),
        ),
    ]
