# Generated by Django 2.0.8 on 2018-11-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20181123_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fields',
            field=models.ManyToManyField(blank=True, null=True, to='feedback.FeedbackField'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='score_fields',
            field=models.ManyToManyField(blank=True, null=True, to='feedback.FeedbackScoreField'),
        ),
    ]
