# Generated by Django 2.0.8 on 2018-12-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20181127_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fields',
            field=models.ManyToManyField(blank=True, to='feedback.FeedbackField'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='score_fields',
            field=models.ManyToManyField(blank=True, to='feedback.FeedbackScoreField'),
        ),
    ]
