# Generated by Django 2.0.8 on 2019-02-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_annotationfeedback_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationfeedback',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
