# Generated by Django 2.0.8 on 2019-10-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20190228_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('NONE', 'None'), ('BINARY', 'Binary'), ('QUIZ', 'Quiz'), ('POINTS', 'Points'), ('NER', 'NER'), ('CLASSIFICATION', 'Classification')], default='NONE', max_length=32),
        ),
    ]
