# Generated by Django 2.0.8 on 2019-11-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_auto_20191105_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationfeedback',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
