# Generated by Django 2.2 on 2019-11-11 23:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_auto_20191106_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='autoreject',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='annotationfeedback',
            name='scores',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='annotationfeedback',
            name='values',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
