# Generated by Django 2.0.8 on 2018-11-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplatefield',
            name='feedback',
            field=models.BooleanField(default=True),
        ),
    ]
