# Generated by Django 2.0.7 on 2018-10-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtemplate',
            name='max_annotations',
        ),
        migrations.RemoveField(
            model_name='itemtemplate',
            name='multiple_annotations',
        ),
        migrations.AddField(
            model_name='task',
            name='max_annotations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='multiple_annotations',
            field=models.BooleanField(default=False),
        ),
    ]
