# Generated by Django 2.0.8 on 2018-11-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_itemtemplatefield_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtemplatefield',
            name='feedback',
            field=models.BooleanField(default=False),
        ),
    ]
