# Generated by Django 2.0.7 on 2018-10-03 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_strategy', '0002_auto_20181003_2152'),
        ('tasks', '0002_auto_20181003_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='strategy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order_strategy.Strategy'),
            preserve_default=False,
        ),
    ]
