# Generated by Django 2.0.8 on 2018-12-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_annotation_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplatefield',
            name='type',
            field=models.CharField(choices=[('INT', 'INT'), ('STR', 'STR'), ('BOOL', 'BOOL'), ('LIST', 'LIST')], default='STR', max_length=10),
        ),
    ]
