# Generated by Django 2.0.8 on 2018-12-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_itemtemplatefield_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtemplatefield',
            name='type',
            field=models.CharField(choices=[('int', 'int'), ('str', 'str'), ('bool', 'bool'), ('list', 'list')], default='str', max_length=10),
        ),
    ]
