# Generated by Django 2.0.8 on 2018-12-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20181207_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
