# Generated by Django 2.0.8 on 2018-12-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20181209_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='instruction',
            field=models.TextField(blank='', default=''),
        ),
    ]
