# Generated by Django 2.0.8 on 2019-02-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20190206_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('IN_PROGRESS', 'IN_PROGRESS'), ('VERIFICATION', 'VERIFICATION'), ('FINISHED', 'FINISHED')], default='NEW', max_length=20),
        ),
    ]
