# Generated by Django 2.0.8 on 2019-03-02 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_auto_20190302_2242'),
        ('tasks', '0012_auto_20190206_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='item',
            name='document',
        ),
        migrations.AddField(
            model_name='item',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packages.Package'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
