# Generated by Django 2.0.8 on 2019-03-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20190302_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('IN_PROGRESS', 'IN_PROGRESS'), ('VERIFICATION', 'VERIFICATION'), ('FINISHED', 'FINISHED')], default='NEW', max_length=20),
        ),
    ]
