# Generated by Django 2.0.8 on 2019-03-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_itemtemplatefield_validate_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
