# Generated by Django 2.0.8 on 2019-03-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_itemtemplatefield_validate_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplatefield',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
