# Generated by Django 2.0.8 on 2019-05-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20190322_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='keywords',
            field=models.CharField(default='', max_length=100),
        ),
    ]
