# Generated by Django 2.0.8 on 2019-05-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_task_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
