# Generated by Django 2.0.8 on 2019-05-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_auto_20190503_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplatefield',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
