# Generated by Django 2.0.8 on 2019-07-23 21:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_itemtemplatefield_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='keywords',
        ),
        migrations.AddField(
            model_name='mission',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
