# Generated by Django 2.0.8 on 2019-08-18 19:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20190812_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
