# Generated by Django 2.0.8 on 2019-08-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_usermissionprogress_usertaskprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermissionprogress',
            name='done_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertaskprogress',
            name='done_items',
            field=models.IntegerField(default=0),
        ),
    ]
