# Generated by Django 2.0.8 on 2019-08-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20190822_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermissionprogress',
            old_name='done_tasks',
            new_name='tasks_done',
        ),
        migrations.RenameField(
            model_name='usertaskprogress',
            old_name='done_items',
            new_name='items_done',
        ),
    ]
