# Generated by Django 2.0.8 on 2019-10-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_auto_20190824_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotated',
            field=models.BooleanField(default=False),
        ),
    ]
