# Generated by Django 2.0.8 on 2019-10-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_annotation_annotated'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='exp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
