# Generated by Django 2.0.8 on 2019-11-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_auto_20191104_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
