# Generated by Django 2.2 on 2019-11-07 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_annotation_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Mission'),
        ),
        migrations.AddField(
            model_name='usermissionprogress',
            name='status',
            field=models.CharField(choices=[('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked'), ('IN_PROGRESS', 'InProgress'), ('FINISHED', 'Finished')], default='LOCKED', max_length=32),
        ),
    ]
