# Generated by Django 2.2 on 2019-11-10 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_auto_20191107_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='usertaskprogress',
            name='status',
            field=models.CharField(choices=[('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked'), ('IN_PROGRESS', 'InProgress'), ('FINISHED', 'Finished')], default='LOCKED', max_length=32),
        ),
    ]
