# Generated by Django 2.2.7 on 2019-11-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_auto_20191111_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='instruction',
            field=models.TextField(blank='', default='', null=True),
        ),
    ]
