# Generated by Django 2.2.7 on 2019-11-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_auto_20191128_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='instruction',
            field=models.TextField(blank=True, default=''),
        ),
    ]
