# Generated by Django 2.2.7 on 2019-12-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_auto_20191128_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='instruction',
            field=models.TextField(blank=True, default=''),
        ),
    ]
