# Generated by Django 2.2.7 on 2019-12-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_mission_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtemplatefield',
            name='label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
