# Generated by Django 2.2.4 on 2020-02-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_auto_20200130_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtemplatefield',
            name='label',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
