# Generated by Django 2.2.4 on 2020-03-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_auto_20200315_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='permanent_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertaskprogress',
            name='status',
            field=models.CharField(choices=[('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked'), ('IN_PROGRESS', 'InProgress'), ('FINISHED', 'Finished'), ('PERMANENT', 'Permanent')], max_length=32),
        ),
    ]
