# Generated by Django 2.2.4 on 2020-06-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_auto_20200315_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtemplate',
            options={},
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
