# Generated by Django 2.2.4 on 2020-09-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_auto_20200804_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('IN_PROGRESS', 'IN_PROGRESS'), ('VERIFICATION', 'VERIFICATION'), ('FINISHED', 'FINISHED'), ('PERMANENT', 'PERMANENT')], default='NEW', max_length=20),
        ),
    ]
