# Generated by Django 2.0.7 on 2018-10-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name_plural': 'Strategies'},
        ),
    ]
