# Generated by Django 2.0.8 on 2018-10-30 20:04

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20181022_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='items',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='packages', to='tasks.Item'),
        ),
    ]
