# Generated by Django 2.0.8 on 2019-03-02 22:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20181101_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='items',
        ),
        migrations.AddField(
            model_name='package',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('IN_PROGRESS', 'IN_PROGRESS'), ('VERIFICATION', 'VERIFICATION'), ('FINISHED', 'FINISHED')], default='NEW', max_length=20),
        ),
    ]
