# Generated by Django 2.2.4 on 2020-02-16 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0006_auto_20190302_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPackageProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_done', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NONE', 'None'), ('IN_PROGRESS', 'InProgress'), ('FINISHED', 'Finished')], default='NONE', max_length=32)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
