# Generated by Django 2.2.4 on 2020-06-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_auto_20200518_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('NONE', 'None'), ('IN_PROGRESS', 'InProgress'), ('FINISHED', 'Finished'), ('VERIFICATION', 'Verification'), ('CLOSED', 'Closed')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpackageprogress',
            name='status',
            field=models.CharField(choices=[('NONE', 'None'), ('IN_PROGRESS', 'InProgress'), ('FINISHED', 'Finished'), ('CLOSED', 'Closed')], default='NONE', max_length=32),
        ),
    ]
