# Generated by Django 2.2.4 on 2020-06-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_auto_20200606_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='instruction',
            field=models.TextField(blank=True, default=''),
        ),
    ]
