# Generated by Django 2.0.2 on 2018-03-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20180313_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_path',
            new_name='image_url',
        ),
    ]
