# Generated by Django 2.0.2 on 2018-03-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20180325_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
