# Generated by Django 2.0.2 on 2018-03-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_text_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ImageFile_file'),
        ),
    ]
